### ISSUE TITLE
Ensure Prefabs have Unit and HitPointManager

### ISSUE THREAD

**Issue by knight1219** [WulframIII/wulfram3#1]
As I was testing cargo deployment last night, I found that some of the prefabs we have do not have all of the correct components. At a minimum, they must have a Unit and HitPointManager script add.

**Comment by Cheebsta** [comment]
Note: I've tried to ensure that the new Wulfram3/Resources Prefabs contain both components as well as Photon views. 

- Aberrations may arise from Prefabs in the root Resources folder which some code is still using.

**Comment by knight1219** [comment]
I think we can safely close this issue. All prefabs now have these in them.
