### ISSUE TITLE
Tank can still jump when landed, causing the sound and using fuel.

### ISSUE THREAD

**Issue by Derth55** [WulframIII/wulfram3#23]
you can jump when the tank is landed. nothing happens but it makes the sound and uses fuel.

**Comment by Cheebsta** [comment]
Could you jump from landed in the old game? I want to say yes, but I sort of remember slapping the take off button real quick too.

- Knight made it so the jump attempt is ignored for now. Same with pulse while landed.

**Comment by Cheebsta** [comment]
This should be okay to close bug wise. Addressed in the new landing code. Current behavior should allow the tank to jump and restore the desired height to a reasonable level. Jumping should also break/cancel landing attempts.
