### ISSUE TITLE
Cargo should deploy as team that deployed it

### ISSUE THREAD

**Issue by knight1219** [WulframIII/wulfram3#3]
No matter what type of prefab a cargo deploys as, it should always take on the team of the player that deploys it.

**Comment by Cheebsta** [comment]
Enemy cargo should only be dropped, with repair pad changing the team

**Comment by knight1219** [comment]
That how it was before right? I always thought it was be awesome to steal their cargo and then deploy it and its your's. 

If you cant deploy it, just destroy it.

But that's just me. Thoughts?

**Comment by Cheebsta** [comment]
Definitely not opposed to changing it. It would make protecting cargo more important.

**Comment by knight1219** [comment]
@Cheebsta and @GotchaPython , shall we change cargo deploy so that enemy cargo can be deployed as your own? My vote is yes
- [x] Yes
- [ ] No

**Comment by Cheebsta** [comment]
(from chat) Yes, or possibly a "cargo hack" ability

**Comment by Cheebsta** [comment]
New cargo prefabs should have increased flexibility here.

**Comment by Cheebsta** [comment]
New cargo functions pull team from the unit that carries the box, but deployment code is not yet completed. Vehicle will retain original information for stat keeping purposes (stolen cargo).
