### ISSUE TITLE
Minimap requires click to center after spawn

### ISSUE THREAD

**Issue by Cheebsta** [WulframIII/wulfram3#30]

**Comment by Derth55** [comment]
b4 the mouse click
![image](https://user-images.githubusercontent.com/35212336/34959096-c2677f0c-fa02-11e7-8180-2dd442d2cbe6.png)
after the click
![image](https://user-images.githubusercontent.com/35212336/34959107-d6d8bf00-fa02-11e7-905b-ecabb24e69b4.png)
