### ISSUE TITLE
Projectiles should detonate from splash damage?

### ISSUE THREAD

**Issue by Cheebsta** [WulframIII/wulfram3#31]
The old mechanic for this could get a little strange. I'm unsure what to implement:

- A hitpoint system like any other unit.
- An instant detonation.
- A lifetime penalty (lifetime was implemented in the flak update)

And in the case they survive the splash:
- Roll off course at the whim of the physics engine
- Stay on course
- Deviate from course, but maintain forward direction/normal rotation

**Comment by Derth55** [comment]
REFERENCE
first flak shots
![image](https://user-images.githubusercontent.com/35212336/34959563-10be1196-fa05-11e7-866e-c6816511269d.png)
flak shooting same pulse again
![image](https://user-images.githubusercontent.com/35212336/34959591-2f41630c-fa05-11e7-84bd-d02d4d358dc1.png)

**Comment by Cheebsta** [comment]
I was waiting for input on what to do with them
