### ISSUE TITLE
spawn map needs to show players

### ISSUE THREAD

**Issue by Derth55** [WulframIII/wulfram3#38]
the arrow, or dot would work.

**Comment by Cheebsta** [comment]
I see player icons. Their color is over saturated, but I see them.

The player icons also need moved up to depth 2 or 3 to make sure they stay on top.

**Comment by Derth55** [comment]
icons should be downsized by 50%, and the blue should be lightened a few shades. would be a good start.
![image](https://user-images.githubusercontent.com/35212336/34959859-578fda72-fa06-11e7-9dd8-e81c3da7c674.png)

**Comment by Cheebsta** [comment]
Derth confirmed fixed
