### ISSUE TITLE
landing effect

### ISSUE THREAD

**Issue by Derth55** [WulframIII/wulfram3#42]
if you drive and hold the land button, it plays the liftoff sound over n over, and the tank doesn't land when driving and the lower command is pressed, it should just lower you to the min altitude, and you have to let off all movement commands to land.

**Comment by Derth55** [comment]
do we want mouse movement to cause takeoff as well??

**Comment by Cheebsta** [comment]
Current behavior requires mouse movement for takeoff instead of keys. Still unsure what the original behavior was here.
