### ISSUE TITLE
tank speed it too fast.

### ISSUE THREAD

**Issue by Derth55** [WulframIII/wulfram3#44]
the tank should be half the speed it is now, if not even slower.  But needs the boost ability that consumes fuel 100% faster

**Comment by Derth55** [comment]
cheeb is working on this, hasn't implemented anything as of yet.

**Comment by Derth55** [comment]
the strafing seems to be about right, but the forward n reverse are too fast for stock movement.

**Comment by Cheebsta** [comment]
Velocity limits have been implemented. Need tuning. Same with the thrust values.
