### ISSUE TITLE
spawn map bugs.

### ISSUE THREAD

**Issue by Derth55** [WulframIII/wulfram3#46]

**Comment by Derth55** [comment]
building and running the game makes the spawn ui broken, and misaligned.

**Comment by Derth55** [comment]
when in the spawn screen, if someone connects both tank icons become visible on the map b4 u spawn.
![image](https://user-images.githubusercontent.com/35212336/34956883-1f628c88-f9f9-11e7-99c9-99a6d7c6c0aa.png)
![image](https://user-images.githubusercontent.com/35212336/34956921-474874c4-f9f9-11e7-9d5f-c07d62935689.png)

**Comment by Derth55** [comment]
it happens when anyone joins, u can see them under the map in game, and in the map view too.

**Comment by Cheebsta** [comment]
Derth confirms fixed
