### ISSUE TITLE
killing someone burns their name into your screen, and after respawn they are invisible.

### ISSUE THREAD

**Issue by Derth55** [WulframIII/wulfram3#47]
yah tired it a few times,  when u kill yourself or die, that name gets burnt onto the screen of another player, stays after they re spawn too.  they become invisible, i can hear the tank but cant see it after death and re spawn.

**Comment by Derth55** [comment]
![image](https://user-images.githubusercontent.com/35212336/34957207-a6c0e354-f9fa-11e7-8eac-811e8fc4a866.png)
name still burnt and invisible tank after death. 
![image](https://user-images.githubusercontent.com/35212336/34957269-dff9cd3e-f9fa-11e7-8ba6-17a5b75a6321.png)
invisible view. and red tank still has name cuz it hasn't died.
![image](https://user-images.githubusercontent.com/35212336/34957306-0a3a3da4-f9fb-11e7-8828-f7de99563c19.png)

**Comment by Cheebsta** [comment]
Derth has also confirmed he can can no longer reproduce and asked to close
