### ISSUE TITLE
tank re spawn bug

### ISSUE THREAD

**Issue by Derth55** [WulframIII/wulfram3#64]
after death and re spawn the tank becomes invisible to all units turrets, radar, and map.  cant lock onto them but they can play normal and lock onto and kill anything, only the counter at the top shows their in game.
the blue tank hasn't re spawned.
![image](https://user-images.githubusercontent.com/35212336/35005612-fb3cd59c-fac1-11e7-8065-cfc24eb40bd6.png)
other view.
![image](https://user-images.githubusercontent.com/35212336/35005649-1c7be50e-fac2-11e7-8b3b-dc958f954bd0.png)

**Comment by Cheebsta** [comment]
I believe this is fixed
